jenkins:
        image: docker.io/jenkins:latest
        ports:
           - "8080:8080"
           - "50000:50000"
        volumes:
           - "/home/jenkins:/var/jenkins_home"
           - "/etc/localtime:/etc/localtime"
        restart: always
